// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0gvbSI1v2omQ9kvE-w4SjVohlCHNxHEo',
    appId: '1:1020489811715:web:19162a69855b1565394b36',
    messagingSenderId: '1020489811715',
    projectId: 'campus--plug',
    authDomain: 'campus--plug.firebaseapp.com',
    storageBucket: 'campus--plug.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC46_qAju-qh0Eh26Wrzvai4D-msLvCtWg',
    appId: '1:1020489811715:android:9a8c8e291d1cfa71394b36',
    messagingSenderId: '1020489811715',
    projectId: 'campus--plug',
    storageBucket: 'campus--plug.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5s-dk-lfHvgT5XBauq6zr2bB6QVRlGWo',
    appId: '1:1020489811715:ios:ecc8df6175c1700e394b36',
    messagingSenderId: '1020489811715',
    projectId: 'campus--plug',
    storageBucket: 'campus--plug.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5s-dk-lfHvgT5XBauq6zr2bB6QVRlGWo',
    appId: '1:1020489811715:ios:ecc8df6175c1700e394b36',
    messagingSenderId: '1020489811715',
    projectId: 'campus--plug',
    storageBucket: 'campus--plug.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0gvbSI1v2omQ9kvE-w4SjVohlCHNxHEo',
    appId: '1:1020489811715:web:77cdfac3e92ac02f394b36',
    messagingSenderId: '1020489811715',
    projectId: 'campus--plug',
    authDomain: 'campus--plug.firebaseapp.com',
    storageBucket: 'campus--plug.firebasestorage.app',
  );
}
